name: CI/CD Pipeline

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Instalar dependências
      run: npm install
    
    - name: Executar testes unitários
      run: npm run test
    
    - name: Resultado dos testes
      if: always()
      run: echo "Testes finalizados!"